### PR TITLE
Improve gui

### PR DESCRIPTION
**Pull request by hdsingh**
## Tasks
- [x] for the given data volume, to be able to select among the three axes of projection, XY, XZ, YZ
- [x] for each of those axes to be able to select any index of plane to show
- [x] to resize/rename the plot axes to accurately reflect the current selection
- [x] (bonus) to provide a choice of colour-maps to render with (see [palettes](https://bokeh.pydata.org/en/latest/docs/reference/palettes.html))
- [x] (bonus) to rewrite the code using [parameters](https://panel.pyviz.org/user_guide/Param.html)

Please let me know what else needs to be changed and further steps.
Thanks!!

### CODE REVIEW

**Comment by martindurant** [comment]
Thank you, @hdsingh , this is just the kind of solution that I had in mind. 
Do you have any thoughts about the capabilities of the hv visualisations or panel/param as an in-browser GUI toolkit? 
Can you conceive of more complex interaction patterns that could not be well-handled by param, but would require the watch/callback mechanism, which is more like traditional GUI messaging? I must admit, you made it look fairly easy.

**Comment by hdsingh** [comment]
Thanks a lot for your reviews @martindurant . 

Holoviews, Panel, Param and Intake are absolutely amazing. The entire pyviz has not only removed difficulty and syntax complexity from in-browser GUI, plotting but also added immense beauty to it. It has really raised the standards. This is the way plotting should be done in python. Being involved in the data science, after knowing about these libraries I felt that I found out the peice that I was always missing. Pyviz being comparatively new is less popular as of now however I feel that these libraries are going to be extremely popular in data science community in the near future and are completely going to replace simple matplotlib and seaborn graphs. The features that entire pyviz provides are awesome. Everyone would love to work with these tools.

I will design a dashboard on another dataset having some complex interaction patterns by using watch/callback mechanism as soon as possible and let you know.
I am also thinking about writing a blogpost on amazing GUI capablities of hv,panel and intake. 

Thanks!!

**Comment by jbednar** [comment]
Thank *you*, @hdsingh!  It's great to hear that our work is appreciated. A blog post would be great to see!

**Comment by hdsingh** [comment]
### Watch/callback mechanism
@martindurant 
There was a problem with the earlier dashboard. Axes `XY`, `XZ`, `YZ` have **68, 189, 157** number of images.
However Index slider was constant, showed 189 indexes for every axes. For `XY` and `YZ` blank images were shown after index **68** and **157**. This has been solved by creating a custom callback function so that it:
1. Resets index to 0 whenever axis is changed.
2. Resets `end` of index slider according to number of images in that axes.

The event of Index change is now handled by callback function.

**Comment by hdsingh** [comment]
@jbednar Sure sir, I would let you know when the blog post is ready.
Thanks!!

**Comment by hdsingh** [comment]
@martindurant Shall we merge or close this PR?

**Comment by martindurant** [comment]
Yes, this can be merged, and then it stays a permanent record of the preliminary work.

**Comment by hdsingh** [comment]
Thanks for the clarification.

**Pull request merged**
